import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "./components/shared/Navbar";
import Footer from "./components/shared/Footer";
import Marquee from "./components/Marquee";
import { ToastContainer } from "react-toastify";

const notoSerifBengli = Noto_Serif_Bengali({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bazar Dor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifBengli.className} h-full antialiased`}
    >
      <body className="flex flex-col min-h-screen ">
        <Navbar />
        <Marquee />
        <main className=" flex-1">{children}</main>
        <ToastContainer />
        <Footer />
      </body>
    </html>
  );
}
